"""add guardian_verification_requests table

Revision ID: a4de9467c993
Revises: 122e4df40d77
Create Date: 2026-04-07 10:47:09.386327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4de9467c993'
down_revision = '122e4df40d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_verification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capsule_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardian_verification_requests', schema=None) as batch_op:
        batch_op.create_index('ix_guardian_req_capsule_status', ['capsule_id', 'status'], unique=False)
        batch_op.create_index('ix_guardian_req_token', ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardian_verification_requests_token'), ['token'], unique=True)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_capsule_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_owner_id'))
        batch_op.drop_table_comment(
        existing_comment='Files (photos, videos, documents) linked to capsules'
    )

    with op.batch_alter_table('capsule_guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capsule_guardians_capsule_id'))
        batch_op.drop_index(batch_op.f('ix_capsule_guardians_guardian_id'))
        batch_op.drop_table_comment(
        existing_comment='Junction table for Capsule-Guardian many-to-many relationship'
    )

    with op.batch_alter_table('capsule_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capsule_recipients_capsule_id'))
        batch_op.drop_index(batch_op.f('ix_capsule_recipients_recipient_id'))
        batch_op.drop_table_comment(
        existing_comment='Junction table for Capsule-Recipient many-to-many relationship'
    )

    with op.batch_alter_table('capsules', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Core entity containing encrypted messages and metadata'
    )

    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Records of capsule delivery attempts'
    )

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardians_owner_id'))
        batch_op.drop_table_comment(
        existing_comment='Trusted verifiers for event-based capsule releases'
    )

    with op.batch_alter_table('heartbeat_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heartbeat_user_id'))
        batch_op.drop_table_comment(
        existing_comment='Periodic still alive pings for inactivity-based triggers'
    )

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipients_owner_id'))
        batch_op.drop_table_comment(
        existing_comment='People who will receive capsules (e.g., children, friends)'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_table_comment(
        existing_comment='Account owners who create and manage time capsules'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Account owners who create and manage time capsules',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.create_table_comment(
        'People who will receive capsules (e.g., children, friends)',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('ix_recipients_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('heartbeat_checks', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Periodic still alive pings for inactivity-based triggers',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('ix_heartbeat_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Trusted verifiers for event-based capsule releases',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('ix_guardians_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Records of capsule delivery attempts',
        existing_comment=None
    )

    with op.batch_alter_table('capsules', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Core entity containing encrypted messages and metadata',
        existing_comment=None
    )

    with op.batch_alter_table('capsule_recipients', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Junction table for Capsule-Recipient many-to-many relationship',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('ix_capsule_recipients_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capsule_recipients_capsule_id'), ['capsule_id'], unique=False)

    with op.batch_alter_table('capsule_guardians', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Junction table for Capsule-Guardian many-to-many relationship',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('ix_capsule_guardians_guardian_id'), ['guardian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capsule_guardians_capsule_id'), ['capsule_id'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Files (photos, videos, documents) linked to capsules',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('ix_attachments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_capsule_id'), ['capsule_id'], unique=False)

    with op.batch_alter_table('guardian_verification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardian_verification_requests_token'))
        batch_op.drop_index('ix_guardian_req_token')
        batch_op.drop_index('ix_guardian_req_capsule_status')

    op.drop_table('guardian_verification_requests')
    # ### end Alembic commands ###
